name = "wagwanspark-beat-store"
main = "src/index.js"
compatibility_date = "2024-01-15"

[assets]
directory = "public"
binding = "ASSETS"

[env.production]
name = "wagwanspark-beat-store-prod"
route = "example.com/*"
